"""Generate docker-compose.yml from a DockerEnvironment snapshot.

Takes the same frozen model objects that the auditor and renderer use.
Produces a valid compose file that recreates the running environment.
"""

from __future__ import annotations

from io import StringIO

from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap, CommentedSeq

from roustabout.models import ContainerInfo, DockerEnvironment

# Labels managed by compose — exclude from generated output
_COMPOSE_LABEL_PREFIXES = (
    "com.docker.compose.",
    "com.docker.desktop.",
)

# Default Docker networks that shouldn't be declared in top-level networks:
_DEFAULT_NETWORKS = {"bridge", "host", "none"}


def generate(
    env: DockerEnvironment,
    *,
    include_stopped: bool = False,
    project_name: str | None = None,
) -> str:
    """Generate a docker-compose.yml from a DockerEnvironment.

    Args:
        env: The environment snapshot to convert.
        include_stopped: Include stopped containers (default: running only).
        project_name: Optional compose project name for the x-project comment.

    Returns:
        A valid docker-compose.yml as a string.
    """
    containers = list(env.containers)
    if not include_stopped:
        containers = [c for c in containers if c.status == "running"]

    if not containers:
        return "# No running containers found.\n"

    doc = CommentedMap()
    doc.yaml_set_comment_before_after_key(
        "services",
        before=_header_comment(env, containers, include_stopped),
    )

    # Build services
    services = CommentedMap()
    all_volumes: set[str] = set()
    all_networks: set[str] = set()

    for container in containers:
        service_name = _service_name(container)
        service = _build_service(container)
        services[service_name] = service

        # Track volumes and networks for top-level declarations
        for mount in container.mounts:
            if mount.type == "volume":
                all_volumes.add(mount.source)
        for net in container.networks:
            if net.name not in _DEFAULT_NETWORKS:
                all_networks.add(net.name)

        # Add compose origin comment
        if container.compose_config_files:
            services.yaml_set_comment_before_after_key(
                service_name,
                before=f"Originally from compose file: {container.compose_config_files}",
            )

    doc["services"] = services

    # Top-level volumes
    if all_volumes:
        volumes = CommentedMap()
        for vol_name in sorted(all_volumes):
            volumes[vol_name] = CommentedMap([("external", True)])
        doc["volumes"] = volumes
        doc.yaml_set_comment_before_after_key(
            "volumes",
            before=(
                "These volumes already exist on this host. To make this file portable,\n"
                "remove 'external: true' — but you'll need to migrate data separately."
            ),
        )

    # Top-level networks
    if all_networks:
        networks = CommentedMap()
        for net_name in sorted(all_networks):
            networks[net_name] = CommentedMap([("external", True)])
        doc["networks"] = networks
        doc.yaml_set_comment_before_after_key(
            "networks",
            before=(
                "These networks already exist on this host. To make this file portable,\n"
                "remove 'external: true' and let compose create them."
            ),
        )

    return _dump_yaml(doc)


def _header_comment(
    env: DockerEnvironment,
    containers: list[ContainerInfo],
    include_stopped: bool,
) -> str:
    running = sum(1 for c in env.containers if c.status == "running")
    stopped = len(env.containers) - running
    scope = f"{len(containers)} containers"
    if not include_stopped and stopped > 0:
        scope += f" ({stopped} stopped excluded)"

    lines = [
        "Generated by roustabout from Docker API snapshot",
        "WARNING: This file may contain secrets in environment variables.",
        "Review before committing to version control.",
        "",
        f"Docker version: {env.docker_version}",
        f"Generated: {env.generated_at}",
        f"Containers: {scope}",
    ]
    return "\n".join(lines)


def _service_name(container: ContainerInfo) -> str:
    """Derive a compose service name from a container."""
    # Use compose service name if available
    if container.compose_service:
        return container.compose_service

    # Sanitize container name for compose
    name = container.name.lstrip("/")
    # Compose service names: lowercase, alphanumeric, hyphens, underscores
    return name.lower().replace(".", "-")


def _is_default_network_mode(mode: str) -> bool:
    """Check if a network mode is a default that shouldn't be emitted."""
    if mode in ("bridge", "default"):
        return True
    # Compose creates {project}_default networks — these are the default behavior
    if mode.endswith("_default"):
        return True
    return False


def _is_auto_hostname(hostname: str) -> bool:
    """Check if a hostname is auto-generated (container ID fragment)."""
    # Docker auto-generates hostnames as 12-char hex strings from the container ID
    import re

    return bool(re.fullmatch(r"[0-9a-f]{12}", hostname))


def _build_service(c: ContainerInfo) -> CommentedMap:
    """Build a compose service definition from a ContainerInfo."""
    svc = CommentedMap()

    svc["image"] = c.image
    svc["container_name"] = c.name

    if c.restart_policy and c.restart_policy != "no":
        svc["restart"] = c.restart_policy

    if c.user:
        svc["user"] = c.user

    if c.privileged:
        svc["privileged"] = True

    if c.init:
        svc["init"] = True

    if c.network_mode and not _is_default_network_mode(c.network_mode):
        # Handle container:X network mode → service:X in compose
        if c.network_mode.startswith("container:"):
            ref_container = c.network_mode.split(":", 1)[1]
            svc["network_mode"] = f"service:{ref_container}"
        else:
            svc["network_mode"] = c.network_mode

    if c.hostname and not _is_auto_hostname(c.hostname):
        svc["hostname"] = c.hostname

    if c.runtime and c.runtime not in ("runc",):
        svc["runtime"] = c.runtime

    if c.pid_mode and c.pid_mode != "":
        svc["pid"] = c.pid_mode

    if c.stop_signal:
        svc["stop_signal"] = c.stop_signal

    if c.stop_grace_period is not None:
        svc["stop_grace_period"] = f"{c.stop_grace_period}s"

    if c.shm_size:
        svc["shm_size"] = _human_bytes(c.shm_size)

    # Ports
    if c.ports:
        ports = CommentedSeq()
        for p in c.ports:
            host_ip = p.host_ip if p.host_ip and p.host_ip != "0.0.0.0" else ""
            ip_prefix = f"{host_ip}:" if host_ip else ""
            port_str = f"{ip_prefix}{p.host_port}:{p.container_port}"
            if p.protocol != "tcp":
                port_str += f"/{p.protocol}"
            ports.append(port_str)
        svc["ports"] = ports

    # Volumes
    volumes = _build_volumes(c)
    if volumes:
        svc["volumes"] = volumes

    # Tmpfs
    if c.tmpfs:
        svc["tmpfs"] = list(c.tmpfs)

    # Networks (skip if using network_mode)
    if not (c.network_mode and not _is_default_network_mode(c.network_mode)):
        nets = _build_networks(c)
        if nets:
            svc["networks"] = nets

    # Environment
    if c.env:
        env_map = CommentedMap()
        for key, value in c.env:
            env_map[key] = value
        svc["environment"] = env_map

    # Labels (excluding compose-internal)
    user_labels = [
        (k, v) for k, v in c.labels if not any(k.startswith(p) for p in _COMPOSE_LABEL_PREFIXES)
    ]
    if user_labels:
        labels = CommentedMap()
        for key, value in user_labels:
            labels[key] = value
        svc["labels"] = labels

    # Healthcheck
    if c.healthcheck:
        svc["healthcheck"] = _build_healthcheck(c)

    # Capabilities
    if c.cap_add:
        svc["cap_add"] = list(c.cap_add)

    if c.cap_drop:
        svc["cap_drop"] = list(c.cap_drop)

    # Devices
    if c.devices:
        svc["devices"] = list(c.devices)

    # Security options
    if c.security_opt:
        svc["security_opt"] = list(c.security_opt)

    # Sysctls
    if c.sysctls:
        sysctls = CommentedMap()
        for key, value in c.sysctls:
            sysctls[key] = value
        svc["sysctls"] = sysctls

    # DNS
    if c.dns:
        svc["dns"] = list(c.dns)

    if c.dns_search:
        svc["dns_search"] = list(c.dns_search)

    # Extra hosts
    if c.extra_hosts:
        svc["extra_hosts"] = list(c.extra_hosts)

    # Group add
    if c.group_add:
        svc["group_add"] = list(c.group_add)

    # Resource limits
    if c.mem_limit or c.cpus:
        deploy = CommentedMap()
        resources = CommentedMap()
        limits = CommentedMap()
        if c.mem_limit:
            limits["memory"] = _human_bytes(c.mem_limit)
        if c.cpus:
            limits["cpus"] = str(c.cpus)
        resources["limits"] = limits
        deploy["resources"] = resources
        svc["deploy"] = deploy

    # Command and entrypoint
    if c.entrypoint:
        svc["entrypoint"] = c.entrypoint

    if c.command:
        svc["command"] = c.command

    return svc


def _build_volumes(c: ContainerInfo) -> CommentedSeq | None:
    """Build the volumes list for a service."""
    if not c.mounts:
        return None

    volumes = CommentedSeq()
    for m in c.mounts:
        if m.type == "bind":
            entry = f"{m.source}:{m.destination}"
            if m.mode and m.mode != "rw":
                entry += f":{m.mode}"
            volumes.append(entry)
        elif m.type == "volume":
            entry = f"{m.source}:{m.destination}"
            if m.mode and m.mode != "rw":
                entry += f":{m.mode}"
            volumes.append(entry)
        # tmpfs mounts are handled separately

    return volumes if volumes else None


def _build_networks(c: ContainerInfo) -> CommentedMap | None:
    """Build the networks section for a service."""
    non_default = [n for n in c.networks if n.name not in _DEFAULT_NETWORKS]
    if not non_default:
        return None

    nets = CommentedMap()
    for n in non_default:
        net_config = CommentedMap()
        # Only include non-default aliases (exclude container name and ID)
        real_aliases = [
            a for a in n.aliases if a != c.name and not a.startswith(c.id[:12]) and a != c.id
        ]
        if real_aliases:
            net_config["aliases"] = list(real_aliases)
        nets[n.name] = net_config if net_config else CommentedMap()

    return nets if nets else None


def _build_healthcheck(c: ContainerInfo) -> CommentedMap:
    """Build healthcheck config from HealthcheckConfig."""
    hc = c.healthcheck
    result = CommentedMap()

    # Convert test command
    test = list(hc.test)
    if test and test[0] == "CMD-SHELL":
        # Single shell command — use the simpler string form
        result["test"] = test[1] if len(test) == 2 else test
    else:
        result["test"] = test

    if hc.interval_ns:
        result["interval"] = _ns_to_duration(hc.interval_ns)
    if hc.timeout_ns:
        result["timeout"] = _ns_to_duration(hc.timeout_ns)
    if hc.retries:
        result["retries"] = hc.retries
    if hc.start_period_ns:
        result["start_period"] = _ns_to_duration(hc.start_period_ns)

    return result


def _ns_to_duration(ns: int) -> str:
    """Convert nanoseconds to a human-readable duration string."""
    seconds = ns // 1_000_000_000
    if seconds >= 60 and seconds % 60 == 0:
        return f"{seconds // 60}m"
    return f"{seconds}s"


def _human_bytes(n: int) -> str:
    """Convert bytes to human-readable size."""
    if n >= 1073741824 and n % 1073741824 == 0:
        return f"{n // 1073741824}G"
    if n >= 1048576 and n % 1048576 == 0:
        return f"{n // 1048576}M"
    if n >= 1024 and n % 1024 == 0:
        return f"{n // 1024}K"
    return str(n)


def _dump_yaml(doc: CommentedMap) -> str:
    """Serialize a CommentedMap to YAML string."""
    yaml = YAML()
    yaml.default_flow_style = False
    yaml.width = 120
    yaml.indent(mapping=2, sequence=4, offset=2)

    stream = StringIO()
    yaml.dump(doc, stream)
    return stream.getvalue()
